# Generated by Django 4.1.5 on 2023-02-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_mytodos_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytodos',
            name='date',
        ),
    ]
