# Generated by Django 4.1.5 on 2023-03-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_remove_mytodos_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytodos',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
